DROP POLICY IF EXISTS leads_am_policy ON leads;
DROP POLICY IF EXISTS tenants_am_policy ON tenants;
DROP FUNCTION IF EXISTS current_country_id();
DROP FUNCTION IF EXISTS current_user_id();
DROP FUNCTION IF EXISTS current_user_role();
ALTER TABLE leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE tenants DISABLE ROW LEVEL SECURITY;

DROP INDEX IF EXISTS idx_tenant_embeddings_embedding;
DROP INDEX IF EXISTS idx_audit_logs_created_at_desc;
DROP INDEX IF EXISTS idx_audit_logs_user_id;
DROP INDEX IF EXISTS idx_audit_logs_entity;
DROP INDEX IF EXISTS idx_sync_results_started_at_desc;
DROP INDEX IF EXISTS idx_sync_results_status;
DROP INDEX IF EXISTS idx_sync_results_sync_run_id;
DROP INDEX IF EXISTS idx_sync_results_tenant_id;
DROP INDEX IF EXISTS idx_ai_recommendations_created_at_desc;
DROP INDEX IF EXISTS idx_ai_recommendations_type;
DROP INDEX IF EXISTS idx_ai_recommendations_status;
DROP INDEX IF EXISTS idx_ai_recommendations_tenant_id;
DROP INDEX IF EXISTS idx_activities_type;
DROP INDEX IF EXISTS idx_activities_next_action_date;
DROP INDEX IF EXISTS idx_activities_tenant_id;
DROP INDEX IF EXISTS idx_activities_lead_id;
DROP INDEX IF EXISTS idx_leads_status;
DROP INDEX IF EXISTS idx_leads_expected_close_date;
DROP INDEX IF EXISTS idx_leads_sector_id;
DROP INDEX IF EXISTS idx_leads_stage;
DROP INDEX IF EXISTS idx_leads_owner_id;
DROP INDEX IF EXISTS idx_tenants_renewal_date;
DROP INDEX IF EXISTS idx_tenants_risk_score_desc;
DROP INDEX IF EXISTS idx_tenants_status;
DROP INDEX IF EXISTS idx_tenants_sector_id;
DROP INDEX IF EXISTS idx_tenants_account_manager_id;
DROP INDEX IF EXISTS idx_users_email;
DROP INDEX IF EXISTS idx_users_keycloak_id;
DROP INDEX IF EXISTS idx_users_country_office_id;
DROP INDEX IF EXISTS idx_users_role;
