apiVersion: v1
kind: ConfigMap
metadata:
  name: htg-crm-config
  namespace: htg-crm-prod
data:
  APP_ENV: production
  HTTP_ADDR: ":8080"
  CORS_ORIGINS: https://crm.htgclouds.com
  REDIS_ADDR: redis:6379
  REDIS_DB: "0"
  CLICKHOUSE_ADDR: clickhouse:9000
  CLICKHOUSE_DATABASE: tenant_analytics
  CLICKHOUSE_USERNAME: htg
  KEYCLOAK_URL: https://auth.htgclouds.com
  KEYCLOAK_REALM: htg-crm
  KEYCLOAK_AUDIENCE: crm-api
  OPENAI_MODEL: gpt-4.1-mini
  NEXTAUTH_URL: https://crm.htgclouds.com
  NEXT_PUBLIC_API_URL: https://api.crm.htgclouds.com
  KEYCLOAK_CLIENT_ID: crm-frontend
